- hosts: webservers
  tasks:
  - name: Create secrets
    shell: "/usr/bin/python3 {{playbook_dir}}/kube_deploy/template_render.py aws-secrets.yaml.jinja2 | /usr/local/bin/kubectl apply -f -"

  - name: Create Pods
    shell: "/usr/bin/python3 {{playbook_dir}}/kube_deploy/template_render.py app-deployment.yaml.jinja2 | /usr/local/bin/kubectl apply -f -"
  
  - name: Create services
    
    shell: "/usr/bin/python3 {{playbook_dir}}/kube_deploy/template_render.py app-service.yaml.jinja2 | /usr/local/bin/kubectl apply -f -"

  - name: Start Ingress
    shell: "/usr/local/bin/kubectl apply -f {{playbook_dir}}/kube_deploy/iam-ingress.yaml"
