- hosts: webservers
  tasks:
  - name: Pip setup
    become: true
    become_method: sudo
    apt:
      pkg: 
      - python3-pip
      - git
      - nginx
  
  - name: Create Known hosts
    shell: "/usr/bin/touch ~/.ssh/known_hosts"
  - name: SSH Known hosts setup
    shell: "/usr/bin/ssh-keyscan -t rsa,dsa github.com 2>&1 | sort -u >> ~/.ssh/known_hosts"
  
  - name: Repo setup
    ansible.builtin.git:
      repo: git@github.com:gautham-nambi/python_iam.git
      dest: "/home/ubuntu/python_iam"
      version: ansible-dev

  - name: Nginx setup
    become: true
    become_method: sudo
    copy:
      remote_src: true
      src: /home/ubuntu/python_iam/nginx.conf
      dest: /etc/nginx/nginx.conf
    
  - name: Nginx reload
    become: true
    become_method: sudo
    shell: "/usr/sbin/nginx -s reload"

  - name: Module setup
    pip:
      requirements: "/home/ubuntu/python_iam/requirements.txt"
      executable: pip3

  - name: Run server
    shell: "/usr/bin/python3 -m gunicorn --bind 127.0.0.1:5000 app:app &"
    args:
      chdir: "/home/ubuntu/python_iam"
    environment:
      AWS_ACCESS_KEY_ID: KEY_ID
      AWS_SECRET_ACCESS_KEY: ACCESS_KEY